# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ayl-beanstalk 0.4.0 ruby lib

Gem::Specification.new do |s|
  s.name = "ayl-beanstalk"
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["j0hnds@gmail.com"]
  s.date = "2015-06-15"
  s.description = "Ayl extension to provide beanstalk support for applications requiring async processing."
  s.email = "j0hnds@gmail.com"
  s.executables = ["ayl_beanstalk", "ayl_worker", "ayl_worker_control"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "ayl-beanstalk.gemspec",
    "bin/ayl_beanstalk",
    "bin/ayl_worker",
    "bin/ayl_worker_control",
    "lib/ayl-beanstalk.rb",
    "lib/ayl-beanstalk/command_line.rb",
    "lib/ayl-beanstalk/engine.rb",
    "lib/ayl-beanstalk/exceptions.rb",
    "lib/ayl-beanstalk/job.rb",
    "lib/ayl-beanstalk/pool.rb",
    "lib/ayl-beanstalk/worker.rb",
    "spec/ayl_worker_control_spec.rb",
    "spec/ayl_worker_spec.rb",
    "spec/command_line_spec.rb",
    "spec/engine_spec.rb",
    "spec/job_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/config/environment.rb",
    "spec/support/exit_code_matchers.rb",
    "spec/worker_spec.rb"
  ]
  s.homepage = "http://github.com/j0hnds/ayl-beanstalk"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.6"
  s.summary = "Ayl extension to provide beanstalk support."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ayl>, ["~> 0.4"])
      s.add_runtime_dependency(%q<beaneater>, ["~> 1.0"])
      s.add_runtime_dependency(%q<daemons>, ["~> 1.1"])
      s.add_development_dependency(%q<rspec>, ["~> 2.14"])
      s.add_development_dependency(%q<bundler>, ["~> 1.10"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<rails>, ["~> 4.1"])
      s.add_development_dependency(%q<pry>, ["~> 0.9"])
    else
      s.add_dependency(%q<ayl>, ["~> 0.4"])
      s.add_dependency(%q<beaneater>, ["~> 1.0"])
      s.add_dependency(%q<daemons>, ["~> 1.1"])
      s.add_dependency(%q<rspec>, ["~> 2.14"])
      s.add_dependency(%q<bundler>, ["~> 1.10"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<rails>, ["~> 4.1"])
      s.add_dependency(%q<pry>, ["~> 0.9"])
    end
  else
    s.add_dependency(%q<ayl>, ["~> 0.4"])
    s.add_dependency(%q<beaneater>, ["~> 1.0"])
    s.add_dependency(%q<daemons>, ["~> 1.1"])
    s.add_dependency(%q<rspec>, ["~> 2.14"])
    s.add_dependency(%q<bundler>, ["~> 1.10"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<rails>, ["~> 4.1"])
    s.add_dependency(%q<pry>, ["~> 0.9"])
  end
end

